### ISSUE TITLE
Avast detects binaries as "potential" virus

### ISSUE THREAD

**Issue by z505** [fredvs/sak#1]
Hi Fred, just a note that Avast finds this as a potential virus in the demos for Windows..

https://github.com/fredvs/sak/releases/download/20150705/win32.zip

Not sure what would trigger it as a potential virus... So I will send them a heads up that it is a false positive?

Avast calls it a rare program that might be a virus, WTF?

**Comment by fredvs** [comment]
Hello.

Thanks to report it and sorry for the late answer.

Huh, I do not understand why, all demos were compiled with fpc 2.6.4.

Do you know if the potential virus comes from the sak-fpc-demos or from espeak executable ?

Thanks.

Fre;D

**Comment by z505** [comment]
I sent the files to Avast and it should be okay now, I'm not sure what triggered it. They likely will add these to the white list.

**Comment by fredvs** [comment]
Hello.

Thanks to do this.

Fre;D
